{
    "openapi": "3.0.2",
    "info": {
        "title": "openInsuranceAPI",
        "version": "0.8.0",
        "description": "open insurance API",
        "contact": {
            "email": "sgutierr@redhat.com"
        },
        "license": {
            "name": "Apache 2.0",
            "url": "https://www.apache.org/licenses/LICENSE-2.0"
        }
    },
    "paths": {
        "/banks": {
            "summary": "Path used to manage the list of banks.",
            "description": "The REST endpoint/path used to list and create zero or more `bank` entities.  This path contains a `GET` and `POST` operation to perform the list and create tasks, respectively.",
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "type": "array",
                                    "items": {
                                        "$ref": "#/components/schemas/bank"
                                    }
                                },
                                "examples": {
                                    "example1": {
                                        "value": [
                                            {
                                                "id": "some text",
                                                "short_name": "some text",
                                                "full_name": "some text",
                                                "logo": "some text",
                                                "website": "some text",
                                                "bank_routing": {
                                                    "scheme": "some text",
                                                    "address": "some text"
                                                }
                                            },
                                            {
                                                "id": "some text",
                                                "short_name": "some text",
                                                "full_name": "some text",
                                                "logo": "some text",
                                                "website": "some text",
                                                "bank_routing": {
                                                    "scheme": "some text",
                                                    "address": "some text"
                                                }
                                            }
                                        ]
                                    }
                                }
                            }
                        },
                        "description": "Successful response - returns an array of `bank` entities."
                    }
                },
                "operationId": "getbanks",
                "summary": "List All banks",
                "description": "Gets a list of all `bank` entities."
            },
            "post": {
                "requestBody": {
                    "description": "A new `bank` to be created.",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/bank"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "201": {
                        "description": "Successful response."
                    }
                },
                "operationId": "createbank",
                "summary": "Create a bank",
                "description": "Creates a new instance of a `bank`."
            }
        },
        "/banks/{bankId}": {
            "summary": "Path used to manage a single bank.",
            "description": "The REST endpoint/path used to get, update, and delete single instances of an `bank`.  This path contains `GET`, `PUT`, and `DELETE` operations used to perform the get, update, and delete tasks, respectively.",
            "get": {
                "responses": {
                    "200": {
                        "content": {
                            "application/json": {
                                "schema": {
                                    "$ref": "#/components/schemas/bank"
                                },
                                "examples": {
                                    "example1": {
                                        "value": {
                                            "id": "some text",
                                            "short_name": "some text",
                                            "full_name": "some text",
                                            "logo": "some text",
                                            "website": "some text",
                                            "bank_routing": {
                                                "scheme": "some text",
                                                "address": "some text"
                                            }
                                        }
                                    }
                                }
                            }
                        },
                        "description": "Successful response - returns a single `bank`."
                    }
                },
                "operationId": "getbank",
                "summary": "Get a bank",
                "description": "Gets the details of a single instance of a `bank`."
            },
            "put": {
                "requestBody": {
                    "description": "Updated `bank` information.",
                    "content": {
                        "application/json": {
                            "schema": {
                                "$ref": "#/components/schemas/bank"
                            }
                        }
                    },
                    "required": true
                },
                "responses": {
                    "202": {
                        "description": "Successful response."
                    }
                },
                "operationId": "updatebank",
                "summary": "Update a bank",
                "description": "Updates an existing `bank`."
            },
            "delete": {
                "responses": {
                    "204": {
                        "description": "Successful response."
                    }
                },
                "operationId": "deletebank",
                "summary": "Delete a bank",
                "description": "Deletes an existing `bank`."
            },
            "parameters": [
                {
                    "examples": {
                        "example1": {
                            "value": "1"
                        }
                    },
                    "name": "bankId",
                    "description": "A unique identifier for a `bank`.",
                    "schema": {
                        "type": "string"
                    },
                    "in": "path",
                    "required": true
                }
            ]
        }
    },
    "components": {
        "schemas": {
            "bank": {
                "title": "Root Type for bank",
                "description": "",
                "type": "object",
                "properties": {
                    "id": {
                        "type": "string"
                    },
                    "short_name": {
                        "type": "string"
                    },
                    "full_name": {
                        "type": "string"
                    },
                    "logo": {
                        "type": "string"
                    },
                    "website": {
                        "type": "string"
                    },
                    "bank_routing": {
                        "type": "object",
                        "properties": {
                            "scheme": {
                                "type": "string"
                            },
                            "address": {
                                "type": "string"
                            }
                        }
                    }
                },
                "example": {
                    "id": "psd201-bank-x--uk",
                    "short_name": "Bank X",
                    "full_name": "The Bank of X",
                    "logo": "https://static.openbankproject.com/images/sandbox/bank_x.png",
                    "website": "https://www.example.com",
                    "bank_routing": {
                        "scheme": "OBP",
                        "address": "psd201-bank-x--uk"
                    }
                }
            }
        },
        "securitySchemes": {
            "user-key": {
                "type": "apiKey",
                "name": "user-key",
                "in": "header"
            }
        }
    },
    "security": [
        {
            "user-key": [
            ]
        }
    ],
    "tags": [
        {
            "name": "Insurance",
            "description": "Insurance sector"
        },
        {
            "name": "OpenBanking",
            "description": "Financial"
        }
    ]
}